spring.datasource.url=${SERVER_DB_URL}

spring.datasource.username=${SERVER_DB_USER_NAME}
spring.datasource.password=${SERVER_DB_PASS}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##jpa config
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true